language: ruby
rvm:
- 2.1.5

branches:
 only:
 - development

before_script:
 - npm install

script:
 - gem install jekyll
 - gem install rouge
 - gulp publish

after_script:
 - git config --global user.email  "mail+travis@droidekas.github.io"
 - git config --global user.name "Travis-CI"
 - gulp deploy

env:
 global:
  secure: Hytqq10mkCScBZM/k45O/mJdYtluhvsJkZCrQtev+LObkR47+FEU+V6W7BsDHp1GQR1Xi9vAL5LkUdZ4oeZtVq326QO5xz79Y+MWztFv9RXHq372YynNujquKtjr3I/TZq+tO47B2q08hlChQ+hw0D+PYo9OIOQ7Fzsu/qBJfPo=
