language: ruby
rvm:
- 2.1.5
branches:
  only:
  - development
  - master
before_script:
- npm install
script:
- gem install rouge
- gem install jekyll
- gulp publish
after_success:
- git config --global user.email  "mail+travis@droidekas.github.io"
- git config --global user.name "Travis-CI"
- gulp deploy
env:
  global:
    secure: IsZVMQSEJjP9HEM5BiTqCNdFvaYtz9ZZLI67XCxymAuRE04DM75tjF+d2xLCtJ8xUDzYVSnyJrB8jWJd/EsgddRxAp2Pm+TtPdp3mzoFNaA43wq6hclNaJB6GYutrlhCbbh/Ck5t3p7asMVk3rx8Jp3vb4cQa3fGkP3siMPfV64=
