# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: My Website
description: Oops..spilled my coffee.
tagline: personal
url: localhost:4000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: droidekas
  email: satyarth.23@gmail.com
  bio: Summon the droidekas!
  twitter: droid_ekas

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: none
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--end-excerpt-->'

# Markdown library
markdown: kramdown
# Markdown library options
# redcarpet:
#   extensions: ['tables', 'fenced_code_blocks', 'autolink', 'smart',
#               'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes','emphasis']
highlighter: true

defaults:
  -
    scope:
      path: ""
    values:
      actions: 
        - label: "@droidekas"
          icon: "ion-social-twitter"
          link: "https://twitter.com/droid_ekas"
        - label: "Github"
          icon: "ion-social-github"
          link: "https://github.com/droidekas"
        - label: "Email"
          icon: "ion-android-mail"
          link: "mailto:satyarth.23@gmail.com"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false
  -
    scope:
      path: ""
      type: "drafts"
    values:
      comments: false